### ISSUE TITLE
Command line version?

### ISSUE THREAD

**Issue by mekocanic** [Algodal/Parser-Generator-Tool-PR#4]
Would be really cool to have, plus i could easier integrate it into a build system for example

could be as simple as `algoparser json.parser generated/`

**Comment by Rickodesea** [comment]
Thanks for the feedback @pink-dev .  The next release will have a command-line application for purposes like what you describe.  I don't have an exact date for the release though.

**Comment by Rickodesea** [comment]
@pink-dev I added the console versions to the current release.  You can download it now.  Even though it says preview, it is production-ready.  That way, you don't have to wait until the next version to get it.

https://algodal.itch.io/algodal-parser-generator-tool/devlog/765439/added-console-version-of-the-parser-generator-app
